GEODE-8738: Updated documentation about WAN deployments with sites wi…
apache/geode pull request #5766
Opened 2020-11-20 09:47 UTC by albertogpz

…th the same IP address and port for all gateway receivers

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

2020-11-20 22:24 UTC, davebarnes97 commented
@albertogpz Thank you for your contribution.
I have edited your text for format and style, but I am unable to push my changes to your fork. I attach the file here so you can incorporate my changes from your side. Please let me know if you'd like to receive these changes in another way.
Best regards, and thanks!
[GEODE-8738-edit.zip](https://github.com/apache/geode/files/5576363/GEODE-8738-edit.zip)

2020-11-20 22:25 UTC, davebarnes97 requested changes
Good material. My review applies to the docs only -- I did not test the code.
Changes submitted in another comment.
Thank you.

2020-11-21 08:46 UTC, albertogpz commented
> @albertogpz Thank you for your contribution.
> I have edited your text for format and style, but I am unable to push my changes to your fork. I attach the file here so you can incorporate my changes from your side. Please let me know if you'd like to receive these changes in another way.
> Best regards, and thanks!
> [GEODE-8738-edit.zip](https://github.com/apache/geode/files/5576363/GEODE-8738-edit.zip)

@davebarnes97 , thanks for the review and the appropriate corrections. I agree to all of them.
Might be good that @boglesby or @bschuchardt take a look at the text too.

2020-12-01 00:26 UTC, alb3rtobr requested changes
LGTM, just fix the typo

2020-12-01 00:26 UTC, alb3rtobr commented on geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb
> +The following output shows how the receiver side would look like after this configuration if 4 gateway recievers were configured:
There is a typo: "recievers"

2020-12-01 09:15 UTC, albertogpz commented on geode-docs/topologies_and_comm/multi_site_configuration/setting_up_a_multisite_system.html.md.erb
> +The following output shows how the receiver side would look like after this configuration if 4 gateway recievers were configured:
Good catch, Alberto! Thanks.

2020-12-01 10:55 UTC, alb3rtobr approved these changes

2020-12-01 18:50 UTC, davebarnes97 approved these changes

2020-12-01 18:51 UTC, merged