GEODE-8745: Fixing the flaky tests.
apache/geode pull request #5821
Opened 2020-12-08 01:43 UTC by nabarunnag

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

2020-12-08 20:17 UTC, nabarunnag commented
* Primary serial sender receives an event but the sender is not running yet. Hence it has to drop the event.
   * Primary has to inform the secondary to remove the event from the unprocessedEventsMap.
   * It has to do that because the event is dropped and the cache listener on the secondary queue will not be triggered to remove it.
   * Hence, the primary sends BatchDestroyOperation to the secondary with the tail key set to -1 to trigger removal from unprocessedEventMap.
   * There is a race in which the BatchDestroyOperation arrives before the secondary event. 
   * In this case the event is never removed from the unprocessedEventsMap.
   * In this fix, if this happens the event ID is placed in the unprocessedTokensMap.
   * So, when the secondary event arrives, it checks the unprocessedTokensMap and then realizes that the primary has seen the event and there is no need to place the event in the unprocessedEventsMap.

2020-12-08 20:18 UTC, nabarunnag commented on geode-core/src/main/java/org/apache/geode/internal/cache/wan/AbstractGatewaySender.java
>            }
Refer line#1035

2020-12-09 09:45 UTC, nabarunnag commented on geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
> +        }
Same logic as in basicHandlePrimaryEntry

2020-12-09 19:26 UTC, DonalEvans requested changes
Just a few code clean-up requests.

2020-12-09 19:26 UTC, DonalEvans commented on geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
> +        }
This empty block can probably be replaced with just a comment.

2020-12-09 19:26 UTC, DonalEvans commented on geode-core/src/main/java/org/apache/geode/internal/cache/wan/serial/SerialGatewaySenderEventProcessor.java
> +            Long.valueOf(System.currentTimeMillis() + AbstractGatewaySender.TOKEN_TIMEOUT);
This can just be `Long mapValue = System.currentTimeMillis() + AbstractGatewaySender.TOKEN_TIMEOUT;`

2020-12-09 19:26 UTC, DonalEvans commented on geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPersistenceEnabledGatewaySenderDUnitTest.java
> +            false, 100, 10, false, true, null, null, true));
These variables are never used, so I think it should be okay to change these to just 
```
vm4.invoke("Creating DS", () -> WANTestBase.createSenderWithDiskStore("ln", 2, false, 100, 10, 
false, true, null, null, true));
vm5.invoke("Creating DS", () -> WANTestBase.createSenderWithDiskStore("ln", 2, false, 100, 10, 
false, true, null, null, true));
```

2020-12-09 19:26 UTC, DonalEvans commented on geode-wan/src/distributedTest/java/org/apache/geode/internal/cache/wan/serial/SerialWANPersistenceEnabledGatewaySenderDUnitTest.java
> +    AsyncInvocation inv1 = vm4.invokeAsync("Starting sender with clean queues",
The compiler warning here can be fixed by using `AsyncInvocation<?> inv1`.

2020-12-09 22:05 UTC, DonalEvans approved these changes

2020-12-09 23:28 UTC, merged