GEODE-8931: Support Redis GETRANGE command
apache/geode pull request #6015
Opened 2021-02-09 17:51 UTC by jdeppe-pivotal

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

2021-02-10 00:33 UTC, nonbinaryprogrammer reviewed
looks good but can you add a test for the right number of command line options?

2021-02-10 14:18 UTC, jdeppe-pivotal commented
> looks good but can you add a test for the right number of command line options?

I think these are the tests you are looking for: https://github.com/apache/geode/blob/1018ece15bca7c58d2f2d8aed414191c04e0532c/geode-redis/src/integrationTest/java/org/apache/geode/redis/internal/executor/string/AbstractGetRangeIntegrationTest.java#L53-L76

2021-02-10 16:05 UTC, sabbey37 requested changes
I was just thinking, we don't have a test verifying the error message when the start/end integers are more than the max value.  The max in Redis is -/+9223372036854775808

2021-02-11 15:57 UTC, sabbey37 approved these changes

2021-02-16 14:49 UTC, merged