GEODE-9285: Implement accurate sizeable for RedisSet
apache/geode pull request #6531
Opened 2021-05-27 20:41 UTC by DonalEvans

- Extend ObjectOpenCustomHashSet to allow direct access to the current
 capacity of the backing array
 - Calculate the overhead associated with each member added based on its
 length
 - Calculate the overhead associated with resizing the backing set in
 RedisSet
 - Update tests to reflect new behaviour

Authored-by: Donal Evans <doevans@vmware.com>

Thank you for submitting a contribution to Apache Geode.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

### Note:
Please ensure that once the PR is submitted, check Concourse for build issues and
submit an update to your PR as soon as possible. If you need help, please send an
email to dev@geode.apache.org.

2021-05-28 21:16 UTC, nonbinaryprogrammer requested changes
looks solid, I just have a couple of small suggestions.
did you run any internal tests for this?

2021-06-01 19:33 UTC, DonalEvans commented on geode-apis-compatible-with-redis/src/main/java/org/apache/geode/redis/internal/collections/SizeableObjectOpenCustomHashSet.java
> +  }
Nice catch, thanks!

2021-06-02 18:47 UTC, nonbinaryprogrammer requested changes
looks good but I think you missed this comment: https://github.com/apache/geode/pull/6531/files/2af372b1bc7a9fd58e5361b8e2289de659461753#r641816516
I'll approve it with that addition

2021-06-02 19:05 UTC, DonalEvans commented
> looks good but I think you missed this comment: https://github.com/apache/geode/pull/6531/files/2af372b1bc7a9fd58e5361b8e2289de659461753#r641816516
> I'll approve it with that addition

Ah, my bad. I originally determined the equation experimentally, not exactly via a test but rather by inspection of the numbers and some educated guesswork, but I've since added a test, `backingArrayOverheadCalculationTest()` that should help determine the formula if it changes.

2021-06-07 13:44 UTC, sabbey37 approved these changes
Looks great!

2021-06-08 16:59 UTC, nonbinaryprogrammer approved these changes

2021-06-08 17:02 UTC, merged