GEODE-9300: write-buffer-size value not used when creating disk store
apache/geode pull request #6596
Opened 2021-06-09 09:06 UTC by alb3rtobr

According to the Geode User Guide, it is possible to set the write buffer size by using the `--write-buffer-size` option when creating a disk store.
Nevertheless, setting a value for that parameter either by using gfsh, cache.xml or the `DiskStoreFactory.setWriteBuffer()` method has no effect.

The current implementation checks if the `WRITE_BUF_SIZE` system property is set, and if that is not the case, the default value of `32768` bytes is used.
This PR changes the behavior so first the disk store write buffer size is obtained (which default value is `32768`). Then, if the `WRITE_BUF_SIZE` system property is set, its value will take precedence over the disk store buffer size.

References:
* `create disk-store` command reference: https://geode.apache.org/docs/guide/113/tools_modules/gfsh/command-pages/create.html
* Question in the dev list about this issue: https://markmail.org/thread/d4ypp7qcw5lfqtf5

2021-06-09 17:44 UTC, DonalEvans commented
This PR needs some tests to confirm that the changes are having the desired effects, i.e. that using the  `--write-buffer-size` gfsh option or the `DiskStoreFactory.setWriteBuffer()` method allows a value other than the default to be set, and that setting the system property `WRITE_BUF_SIZE` overrides these calls.

2021-06-09 22:32 UTC, alb3rtobr commented
> This PR needs some tests to confirm that the changes are having the desired effects, i.e. that using the `--write-buffer-size` gfsh option or the `DiskStoreFactory.setWriteBuffer()` method allows a value other than the default to be set, and that setting the system property `WRITE_BUF_SIZE` overrides these calls.

Ok, Im moving this PR back to draft while I implement the tests

2021-06-11 18:28 UTC, DonalEvans approved these changes
Thanks for adding the tests! I had a thought that might give slightly better test coverage. If the implementation is changed to the below, then you can test that the actual value returned from the system property check is returned from the method, instead of just `null` by mocking the `getWriteBufferSizeProperty()` method to return either null or a non-default value and then asserting that the expected value is returned from `getWriteBufferCapacity()`:
```
  @VisibleForTesting
  Integer getWriteBufferSizeProperty() {
    return Integer.getInteger("WRITE_BUF_SIZE");
  }

  @VisibleForTesting
  Integer getWriteBufferCapacity() {
    Integer writeBufferSizeProperty = getWriteBufferSizeProperty();
    if (writeBufferSizeProperty != null) {
      return writeBufferSizeProperty;
    }
    return getParent().getWriteBufferSize();
  }
```
Just a suggestion, but I think it makes the test a little more robust

2021-06-11 18:28 UTC, DonalEvans commented on geode-core/src/integrationTest/java/org/apache/geode/internal/cache/OplogRVVJUnitTest.java
> +    when(parent.getWriteBufferSize()).thenReturn(32768);
Could hard-coded uses of this value (when it relates to Oplog buffer sizes) be replaced with references to `DiskStoreFactory.DEFAULT_WRITE_BUFFER_SIZE`?

2021-06-11 23:31 UTC, alb3rtobr commented
> 
> Just a suggestion, but I think it makes the test a little more robust

I agree, I think it looks better now. Thanks for the review!

2021-06-14 19:32 UTC, nabarunnag requested changes
Hi Alberto, looking at the commit info you mentioned that the parameter set by gfsh for  --write-buffer-size is ignored by our current implenation, 
It will be nice to see the DUnit test with gfsh commands that fails to set the value and fails but with your fix, the correct value can be seen.

2021-06-16 10:35 UTC, alb3rtobr commented
thanks @nabarunnag , I have implemented a test that fails on develop branch and works after my change. In develop branch it shows that although you can set the write buffer size value and get its value successfully after the disk store creation, the oplog file write buffer has the default value (32768), so the introduced value is ignored.

2021-06-30 17:17 UTC, jinmeiliao approved these changes

2021-06-30 17:17 UTC, jinmeiliao commented on geode-core/src/main/java/org/apache/geode/internal/cache/OverflowOplog.java
> +  @VisibleForTesting
anyway we can avoid duplicating the code?

2021-07-12 11:01 UTC, alb3rtobr commented
Branch rebased to solve conflicts with develop branch.

2021-07-13 07:07 UTC, alb3rtobr commented
hi @nabarunnag , could you remove the request for changes if the tests I implemented are ok for you? Thanks

2021-07-13 16:30 UTC, DonalEvans commented
> hi @nabarunnag , could you remove the request for changes if the tests I implemented are ok for you? Thanks

Not to speak for Naba, but I think his comment was asking for tests that specifically used GFSH commands to set the --write-buffer-size value rather than API calls, as this was part of the problem described in the ticket.

2021-07-13 16:30 UTC, nabarunnag approved these changes

2021-07-13 16:33 UTC, nabarunnag commented
I agree with @DonalEvans

2021-07-28 14:01 UTC, merged