GEODE-9825: Reader Retains Unprocessed Bytes
apache/geode pull request #7131
Opened 2021-11-19 19:14 UTC by Bill

[GEODE-9825](https://issues.apache.org/jira/browse/GEODE-9825)

When `Connection.processInputBuffer()` needed to expand the input buffer, it was also destroying unprocessed data. This resulted in `IOException: "Unknown header byte..."` and hangs.

The `P2PMessagingConcurrencyDUnitTest` has been enhanced to test a matrix of configurations:

[conserve-sockets, useTLS, socket-buffer-size for sender, socket-buffer-size for receiver]

true, true, 32768, 32768
true, true, 65536, 32768
true, false, 32768, 32768
true, false, 65536, 32768
false, true, 32768, 32768
false, true, 65536, 32768
false, false, 32768, 32768
false, false, 65536, 32768

Without the fix in this PR, these were the test results:

![Screen Shot 2021-11-19 at 11 04 46 AM](https://user-images.githubusercontent.com/4002/142678670-08e52b49-d180-483e-80a2-6cd365558e90.png)

- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

2021-11-19 19:33 UTC, dschneider-pivotal approved these changes

2021-11-19 19:34 UTC, pivotal-jbarrett requested changes

2021-11-19 19:34 UTC, pivotal-jbarrett commented on geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
> +@RunWith(JUnitParamsRunner.class)
You need the category params runner or delete the category, without that runner the category is ignored.

2021-11-19 19:34 UTC, pivotal-jbarrett commented on geode-core/src/main/java/org/apache/geode/internal/tcp/Connection.java
> +                  // we're returning to the caller (done == true) so make buffer writable
If we have to comment it to make it readable perhaps it deserves a well named method.
```java
...
makeWriteable(inputBuffer);
...

void makeWriteable(final ByteByffer buffer) {
  buffer.position(buffer.limit());
  buffer.limit(buffer.capacity());
}
```
Now this method is unit testable too.

2021-11-19 20:32 UTC, boglesby approved these changes

2021-11-19 20:45 UTC, Bill commented
Ooh the stress test found a failure!

This fix may be insufficient.

![Screen Shot 2021-11-19 at 12 42 42 PM](https://user-images.githubusercontent.com/4002/142689480-323f106a-fcb2-451c-83b5-4b8cb0d6f755.png)

2021-11-20 00:46 UTC, pivotal-jbarrett approved these changes

2021-11-22 16:06 UTC, Bill commented on geode-core/src/distributedTest/java/org/apache/geode/distributed/internal/P2PMessagingConcurrencyDUnitTest.java
> +      "true, true, 65536, 32768",
done

2021-11-22 18:36 UTC, kamilla1201 approved these changes

2021-11-22 21:25 UTC, agingade approved these changes

2021-11-23 16:29 UTC, merged