GEODE-9969: Fix unescaping the region name with underscore
apache/geode pull request #7282
Opened 2022-01-19 14:37 UTC by mkevo

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [x] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [x] Is your initial contribution a single, squashed commit?

- [x] Does `gradlew build` run cleanly?

- [x] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

2022-01-19 17:05 UTC, DonalEvans requested changes
A few small clean-up requests. Also, if it's not too difficult, would it be possible to get a DUnit test showing the behaviour described in the ticket? It would be good to have confirmation in a test that the user-visible effect of this change is correct.

If it's too difficult to reproduce the issue in a DUnit test then that's okay though.

2022-01-19 17:05 UTC, DonalEvans commented on geode-core/src/test/java/org/apache/geode/internal/cache/PartitionedRegionHelperJUnitTest.java
> +    {
Can these unnecessary braces be removed please?

2022-01-19 19:01 UTC, mkevo commented
> A few small clean-up requests. Also, if it's not too difficult, would it be possible to get a DUnit test showing the behaviour described in the ticket? It would be good to have confirmation in a test that the user-visible effect of this change is correct.
> 
> If it's too difficult to reproduce the issue in a DUnit test then that's okay though.

Hi @DonalEvans,
Thank you for the fast response!
I tried to create DUnit test, but without success.
The main problem with test is how to rename the working dir of the killed server to some other name, so it can be used as a working dir for the new server. 
If you have some idea to do it, please feel free to share it. If not, we also have this test that verifies the solution.

2022-01-19 19:16 UTC, DonalEvans commented
@mkevo I might be wrong, but I think it should be possible to get a new server to use the working directory of a shutdown server using the `--dir` option on the `start server` gfsh command. By default, the directory is named after the server, but you should be able to do something like:
```
start server --name=server1 --server-port=40401

***kill the server***

start server --name=server2 --dir=server1 --server-port=40402
```

2022-01-20 21:26 UTC, kirklund commented
@DonalEvans @mkevo `--dir` won't work in a distributed test (dunit). It will however work in an acceptance test. Take a look at the tests under:
* [geode-assembly/src/acceptanceTest/java/org/apache/geode/serialization/filter/](https://github.com/apache/geode/tree/develop/geode-assembly/src/acceptanceTest/java/org/apache/geode/serialization/filter)
* [geode-assembly/src/acceptanceTest/java/org/apache/geode/logging/](https://github.com/apache/geode/tree/develop/geode-assembly/src/acceptanceTest/java/org/apache/geode/logging)

And (these are older tests so probably not as good):
* [geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers/](https://github.com/apache/geode/tree/develop/geode-assembly/src/acceptanceTest/java/org/apache/geode/launchers)

You can get a reference to the `Process` (to kill it) from `GfshExecution.getProcess()`. `GfshExecution` for that server is returned from `gfshRule.execute(startServerCommand);`

> @mkevo I might be wrong, but I think it should be possible to get a new server to use the working directory of a shutdown server using the `--dir` option on the `start server` gfsh command. By default, the directory is named after the server, but you should be able to do something like:
> 
> ```
> start server --name=server1 --server-port=40401
> 
> ***kill the server***
> 
> start server --name=server2 --dir=server1 --server-port=40402
> ```

2022-01-21 23:08 UTC, dschneider-pivotal approved these changes

2022-01-25 22:56 UTC, DonalEvans approved these changes

2022-01-25 22:58 UTC, merged