GEODE-10020: Introduction of option to gradually activate pinging tow…
apache/geode pull request #7517
Opened 2022-03-30 16:16 UTC by mivanac

…ard destination

### For all changes:
- [*] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [*] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [*] Is your initial contribution a single, squashed commit?

- [*] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

2022-04-01 06:20 UTC, albertogpz commented
> Introduce configurable option to gradually activate pinging toward destination. This can be accomplish by increasing initial delay of each ping task, when endpoint is registering to be in use. After initial delay, current logic is kept, to trigger new ping after ping interval.
> ### For all changes:
> 
>     * [*] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?
> 
>     * [*] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?
> 
>     * [*] Is your initial contribution a single, squashed commit?
> 
>     * [*] Does `gradlew build` run cleanly?
> 
>     * [ ]  Have you written or updated unit tests to verify your changes?
> 
>     * [ ]  If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

What would be the advantage of this change? What would we gain, what would we fix?

2022-04-25 21:05 UTC, pivotal-jbarrett requested changes

2022-04-25 21:05 UTC, pivotal-jbarrett commented on geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
> +    Thread.sleep(maxTimeBetweenPingsInReceiver);
Is there a way to use an `await` here to avoid this arbitrary sleep time.

2022-04-25 21:05 UTC, pivotal-jbarrett commented on geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
> +    int poolEndPointSize = getSenderPoolConnects(vm1, senderId);
When asserting on stats from the `Statistics` types you should `await` on them. They aren't thread safe and my take some time to arrive at the expected result across all threads.

2022-04-25 21:05 UTC, pivotal-jbarrett commented on geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
> +    assertEquals(0, senderPoolDisconnects);
Replace with AssertJ.

2022-04-25 21:05 UTC, pivotal-jbarrett commented on geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
> +      initDelay = (initDelay * OFFSET * NANOS_PER_MS) + pingIntervalNanos;
Also, this should be unit testable and all I see is a very high level acceptance test. Extract a method here that we can unit test.

2022-04-26 19:02 UTC, pivotal-jbarrett requested changes

2022-04-26 19:02 UTC, pivotal-jbarrett commented on geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
> +    offsetIndex.set(0); // Reset counter
If this statement really needs this comment then I suggest making it a method. I also suggest changing the member name a little.

```java
private void resetInitialDelay() {
  intitialDelay.set(0);
}
```

2022-04-26 19:04 UTC, pivotal-jbarrett commented
@mivanac It really concerns me that the only test is a very high level acceptance test. Is there a way to refactor this a little to get some unit test coverage over the changes. Like over the incrementing and resetting of the initial delay / offset? Maybe also around the initial delay calculations.

2022-04-26 22:13 UTC, pivotal-jbarrett requested changes

2022-04-26 22:13 UTC, pivotal-jbarrett commented on geode-core/src/test/java/org/apache/geode/cache/client/internal/LiveServerPingerTest.java
> +import org.junit.Before;
Use JUnit5.

2022-04-27 13:51 UTC, pivotal-jbarrett approved these changes
Just a few minor things I would like to see cleaned but otherwise approved.

2022-04-27 13:51 UTC, pivotal-jbarrett commented on geode-assembly/src/acceptanceTest/java/org/apache/geode/cache/wan/SeveralGatewayReceiversWithSamePortAndHostnameForSendersTest.java
> +      assertNotNull(sender);
Use AssertJ for new test code. 
Would prefer updating whole test to AssertJ.

2022-04-27 13:51 UTC, pivotal-jbarrett commented on geode-core/src/main/java/org/apache/geode/cache/client/internal/LiveServerPinger.java
> +      // At each registration of new endpoint increase counter for calculation of initial delay
I think this comment makes more sense as a javadoc on the method.

2022-04-27 13:51 UTC, pivotal-jbarrett commented on geode-core/src/test/java/org/apache/geode/cache/client/internal/LiveServerPingerTest.java
> +@Category({ClientServerTest.class})
This is unused by JUnit 5 and can just be removed entirely.

2022-04-27 17:07 UTC, pivotal-jbarrett approved these changes

2022-04-27 20:02 UTC, merged