Newfeature2/geode 9484
apache/geode pull request #7664
Opened 2022-05-06 06:25 UTC by mivanac

### For all changes:
- [*] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [*] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [*] Is your initial contribution a single, squashed commit?

- [*] Does `gradlew build` run cleanly?

- [*] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

2022-05-11 18:02 UTC, mivanac commented
Hi  @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
could you review this PR.
Thanks

2022-05-18 11:07 UTC, mivanac commented
Hi @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
could you review this PR.
This was reverted PR with modifications for failing internal test.
Thanks

2022-05-27 14:45 UTC, mivanac commented
Hi @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
just a reminder,
could you review this PR.
This was reverted PR with modifications for failing internal test.
Thanks

2022-06-07 19:21 UTC, mivanac commented
Hi @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
could you review this PR.

2022-06-15 15:13 UTC, mivanac commented
Hi @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
just a reminder,
could you review this PR.
This was reverted PR with modifications for failing internal test.
Thanks

2022-06-23 12:06 UTC, mivanac commented
Hi @Bill, @echobravopapa, @agingade, @kamilla1201 and @pivotal-jbarrett
could you review this PR.

2022-06-28 15:56 UTC, pivotal-jbarrett commented
This PR would probably get more notice with a properly formatted and descriptive title.

2022-06-28 15:59 UTC, pivotal-jbarrett requested changes

2022-06-28 15:59 UTC, pivotal-jbarrett commented on geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDistributedTest.java
> +    return new Integer(server.getPort());
Unnecessary explicit integer boxing.

2022-07-01 05:47 UTC, mivanac commented on geode-core/src/distributedTest/java/org/apache/geode/internal/cache/tier/sockets/UpdatePropagationDistributedTest.java
> +    return new Integer(server.getPort());
Thanks for comments. Updated.

2022-07-01 15:19 UTC, pivotal-jbarrett approved these changes

2022-07-01 15:46 UTC, merged