GEODE-10329: Handle RejectedExecutionException
apache/geode pull request #7721
Opened 2022-05-25 20:04 UTC by DonalEvans

Do not throw RejectedExecutionException if the GMSHealthMonitor is
stopping

Authored-by: Donal Evans <doevans@vmware.com>

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced in the commit message?

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `develop`)?

- [ ] Is your initial contribution a single, squashed commit?

- [ ] Does `gradlew build` run cleanly?

- [ ] Have you written or updated unit tests to verify your changes?

- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?

2022-05-26 15:08 UTC, DonalEvans commented
The failing DUnit test is due to https://issues.apache.org/jira/browse/GEODE-8411, which is a known flaky test and unrelated to the changes in this PR.

2022-05-27 15:54 UTC, gesterzhou approved these changes

2022-06-03 19:25 UTC, pivotal-jbarrett requested changes
I think this should have tests associated with it. If we are explicitly catching and exception and optionally ignoring it there should be tests that cover both cases.

2022-06-04 00:41 UTC, DonalEvans commented
> I think this should have tests associated with it. If we are explicitly catching and exception and optionally ignoring it there should be tests that cover both cases.

I'm going to need some help with writing a test that consistently hits the race condition where the `checkExecutor` is shut down and then attempts to execute something. I wasn't able to reproduce the failure in 2000 runs of the distributed test that originally hit it, and making a unit test for it seems extremely difficult as there is very little visibility into the methods that would need to be stubbed/modified in order to ensure things happen in the order we want.

2022-06-09 18:25 UTC, pivotal-jbarrett commented
@DonalEvans what if we refactored a little to a method that takes function to execute and optionally ignores this specific exception, then we could at least deterministically test that part of the behavior and change in this PR. 🤷 
```java
private void doAndIgnoreRejectedExecutionExceptionIfStopping(final SomeFunctionalnterface someFunctionalThing) {
  try {
    someFunctionalThing.doIt();
  } catch (RejectedExecutionException e) {
    if (!isStopping) {
      throw e;
    }
  }
}

...
      doAndIgnoreRejectedExecutionExceptionIfStopping(() ->
        checkExecutor.execute(() -> {
           try {
             inlineCheckIfAvailable(initiator, cv, true, mbr, reason);
           } catch (MembershipClosedException e) {
             // shutting down
           } catch (Exception e) {
             logger.info("Unexpected exception while verifying member", e);
           }
         }));
...
```



```java
@Test
void doAndIgnoreRejectedExecutionExceptionIfStoppingThrowsWhenNotStopping() {
  gmsHealthMonitor.isStopping = true;
  assertThatThrowBy(() -> gmsHealthMonitor.doAndIgnoreRejectedExecutionExceptionIfStopping(() -> {throw new RejectedExecutionException();})).isInstanceOf(RejectedExecutionException.class);
}
```

2022-06-09 22:20 UTC, DonalEvans commented
@pivotal-jbarrett Thanks for the advice! I think I managed to implement what you suggested; please let me know if it needs further tweaks.

2022-06-09 23:26 UTC, pivotal-jbarrett commented on geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitor.java
> +  void doAndIgnoreRejectedExecutionExceptionIfStopping(final Checker checker) {
Looks like `Runnable` would suffice rather than building our own interface.

2022-06-09 23:27 UTC, pivotal-jbarrett requested changes

2022-06-09 23:27 UTC, pivotal-jbarrett commented on geode-membership/src/test/java/org/apache/geode/distributed/internal/membership/gms/fd/GMSHealthMonitorTest.java
> +import org.junit.Test;
Use JUnit 5.

2022-06-10 02:39 UTC, pivotal-jbarrett approved these changes

2022-06-10 16:27 UTC, merged