GEODE-10366: Cleanup GfshRule created Folder
apache/geode pull request #7791
Opened 2022-06-09 20:12 UTC by kirklund

PROBLEM

Tests using GfshRule default constructor  do not delete the contents
of the internal Folder created by GfshRule when all tests passed. This
results in unnecessary size bloating of the archive file.

SOLUTION

Ensure that GfshRule handles Folder policy and invokes delete when
appropriate.

2022-06-09 20:14 UTC, onichols-pivotal reviewed
Thanks for opting-in to automated commit message feedback via COMMITWATCHERS.  https://cwiki.apache.org/confluence/display/GEODE/Commit+Message+Format suggests that your first commit additional detail paragraph(s) should describe the problem and how this change solves it.

These suggestions are totally optional.  What matters is including enough detail for future contributors to understand what you intended and why.

2022-06-10 16:28 UTC, jinmeiliao approved these changes

2022-06-10 16:52 UTC, demery-pivotal approved these changes

2022-06-13 16:00 UTC, dschneider-pivotal approved these changes

2022-06-19 06:38 UTC, onichols-pivotal requested changes
due to code freeze, please hold off merging this

2022-06-22 22:10 UTC, closed without merging